int16 mr_mtr_sta
int16 mr_flt_msg_err1
int16 mr_flt_msg_err2
int16 mr_flt_msg_warn1
int16 mr_flt_msg_warn2
int16 mr_mtr_curr_real
int16 mr_temp
int16 mr_mtr_rpm_real
int16 mr_mtr_rot_real

int16 ml_mtr_sta
int16 ml_flt_msg_err1
int16 ml_flt_msg_err2
int16 ml_flt_msg_warn1
int16 ml_flt_msg_warn2
int16 ml_mtr_curr_real
int16 ml_temp
int16 ml_mtr_rpm_real
int16 ml_mtr_rot_real

int16 br_mtr_sta
int16 br_flt_msg
int16 br_mtr_curr_real
int16 br_temp
int16 br_mtr_rpm
int16 br_mtr_rot_sta

int16 bl_mtr_sta
int16 bl_flt_msg
int16 bl_mtr_curr_real
int16 bl_temp
int16 bl_mtr_rpm
int16 bl_mtr_rot_sta

int16 sr_str_rpm
int16 sr_str_ang
int16 sl_str_rpm
int16 sl_str_ang
int16 batt400vdc
int16 batt24vdc_1
int16 batt24vdc_2