int16 mr_mtr_run
int16 mr_mtr_rpm
int16 mr_mtr_trq

int16 ml_mtr_run
int16 ml_mtr_rpm
int16 ml_mtr_trq

int16 br_mtr_rot
int16 br_mtr_thr_per

int16 bl_mtr_rot
int16 bl_mtr_thr_per

int16 sr_str_srv_on
int16 st_str_srv_home
int16 sr_str_rpm
int16 sr_str_ang
int16 sr_rfrg

int16 sl_str_srv_on
int16 sl_str_srv_home
int16 sl_str_rpm
int16 sl_str_ang
int16 sl_rfrg

int16 emer_stop
int16 nav_mode
int16 nav_light1
int16 nav_light2
int16 br_s1
int16 br_s2
int16 br_s3
int16 br_s4
int16 pr_s1
int16 pr_s2

int16 bl_s1
int16 bl_s2
int16 bl_s3
int16 bl_s4
int16 pl_s1
int16 pl_s2